DROP TABLE IDS PURGE;
DROP TABLE CANDIDATE_SECURED_RESOURCES PURGE;
DROP TABLE VIEW_RESOURCES_MAPPING PURGE;
DROP TABLE VIEW_RESOURCES PURGE;
DROP TABLE VIEW_HIERARCHY PURGE;
DROP TABLE RESTRICTED_TIMES_ROLES PURGE;
DROP TABLE TIMES_RESOURCES_EXCLUSION PURGE;
DROP TABLE RESTRICTED_TIMES_RESOURCES PURGE;
DROP TABLE RESTRICTED_TIMES PURGE;
DROP TABLE SECURED_RESOURCES_ROLES PURGE;
DROP TABLE SECURED_RESOURCES PURGE;
DROP TABLE ROLES_HIERARCHY PURGE;
DROP TABLE AUTHORITIES PURGE;
DROP TABLE GROUPS_USERS PURGE;
DROP TABLE USERS PURGE;
DROP TABLE GROUPS_HIERARCHY PURGE;
DROP TABLE GROUPS PURGE;
DROP TABLE ROLES PURGE;
-- Sample Application Table
DROP TABLE PRODUCT;
DROP TABLE CATEGORY;


CREATE TABLE GROUPS ( 
  GROUP_ID     VARCHAR2 (20)  NOT NULL, 
  GROUP_NAME   VARCHAR2 (50)  NOT NULL, 
  CREATE_DATE  VARCHAR2 (8), 
  MODIFY_DATE  VARCHAR2 (8), 
  CONSTRAINT PK_GROUPS
  PRIMARY KEY ( GROUP_ID ) ) ; 

CREATE TABLE GROUPS_HIERARCHY ( 
  PARENT_GROUP  VARCHAR2 (50)  NOT NULL, 
  CHILD_GROUP   VARCHAR2 (50)  NOT NULL, 
  CREATE_DATE   VARCHAR2 (8), 
  MODIFY_DATE   VARCHAR2 (8), 
  CONSTRAINT PK_GROUPS_HIERARCHY PRIMARY KEY ( PARENT_GROUP, CHILD_GROUP ),
  CONSTRAINT FK_GROUPS1 FOREIGN KEY (PARENT_GROUP) REFERENCES GROUPS (GROUP_ID),
  CONSTRAINT FK_GROUPS2 FOREIGN KEY (CHILD_GROUP) REFERENCES GROUPS (GROUP_ID) ) ; 

CREATE TABLE USERS ( 
  USER_ID      VARCHAR2 (20)  NOT NULL, 
  USER_NAME    VARCHAR2 (50)  NOT NULL, 
  PASSWORD     VARCHAR2 (50)  NOT NULL, 
  ENABLED      CHAR (1), 
  CREATE_DATE  VARCHAR2 (8), 
  MODIFY_DATE  VARCHAR2 (8), 
  CONSTRAINT PK_USERS
  PRIMARY KEY ( USER_ID ) ) ; 

CREATE TABLE GROUPS_USERS ( 
  GROUP_ID     VARCHAR2 (20)  NOT NULL, 
  USER_ID      VARCHAR2 (20)  NOT NULL, 
  CREATE_DATE  VARCHAR2 (8), 
  MODIFY_DATE  VARCHAR2 (8), 
  CONSTRAINT PK_GROUPS_USERS PRIMARY KEY ( GROUP_ID, USER_ID ),
  CONSTRAINT FK_GROUPS_USERS_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID),
  CONSTRAINT FK_GROUPS_USERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ) ; 

CREATE TABLE ROLES ( 
  ROLE_ID      VARCHAR2 (50)  NOT NULL, 
  ROLE_NAME    VARCHAR2 (50), 
  DESCRIPTION  VARCHAR2 (100), 
  CREATE_DATE  VARCHAR2 (8), 
  MODIFY_DATE  VARCHAR2 (8), 
  CONSTRAINT PK_ROLES PRIMARY KEY ( ROLE_ID ) ) ; 

CREATE TABLE ROLES_HIERARCHY ( 
  PARENT_ROLE  VARCHAR2 (50)  NOT NULL, 
  CHILD_ROLE   VARCHAR2 (50)  NOT NULL, 
  CREATE_DATE  VARCHAR2 (8), 
  MODIFY_DATE  VARCHAR2 (8), 
  CONSTRAINT PK_ROLES_HIERARCHY PRIMARY KEY ( PARENT_ROLE, CHILD_ROLE ),
  CONSTRAINT FK_ROLES1 FOREIGN KEY(PARENT_ROLE) REFERENCES ROLES(ROLE_ID),
  CONSTRAINT FK_ROLES2 FOREIGN KEY(CHILD_ROLE) REFERENCES ROLES (ROLE_ID) ) ; 

CREATE TABLE SECURED_RESOURCES ( 
  RESOURCE_ID       VARCHAR2 (10)  NOT NULL, 
  RESOURCE_NAME     VARCHAR2 (50), 
  RESOURCE_PATTERN  VARCHAR2 (300)  NOT NULL, 
  DESCRIPTION       VARCHAR2 (100), 
  RESOURCE_TYPE     VARCHAR2 (10)  NOT NULL, 
  SORT_ORDER        NUMBER, 
  CREATE_DATE       VARCHAR2 (8), 
  MODIFY_DATE       VARCHAR2 (8), 
  CONSTRAINT PK_RECURED_RESOURCES
  PRIMARY KEY ( RESOURCE_ID ) ) ; 

CREATE TABLE SECURED_RESOURCES_ROLES ( 
  RESOURCE_ID  VARCHAR2 (10)  NOT NULL, 
  ROLE_ID      VARCHAR2 (50)  NOT NULL, 
  CREATE_DATE  VARCHAR2 (8), 
  MODIFY_DATE  VARCHAR2 (8), 
  CONSTRAINT PK_SECURED_RESOURCES_ROLES PRIMARY KEY ( RESOURCE_ID, ROLE_ID ),
  CONSTRAINT FK_SECURED_RESOURCES FOREIGN KEY(RESOURCE_ID) REFERENCES SECURED_RESOURCES(RESOURCE_ID),
  CONSTRAINT FK_ROLES4 FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID) ) ;
  
CREATE TABLE AUTHORITIES ( 
  ROLE_ID      VARCHAR2 (50)  NOT NULL, 
  SUBJECT_ID   VARCHAR2 (20)  NOT NULL, 
  TYPE         VARCHAR2 (2)  NOT NULL, 
  CREATE_DATE  VARCHAR2 (8), 
  MODIFY_DATE  VARCHAR2 (8), 
  CONSTRAINT PK_AUTHORITIES PRIMARY KEY ( ROLE_ID, SUBJECT_ID ),
  CONSTRAINT FK_ROLES3 FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID) ) ; 
  
CREATE TABLE RESTRICTED_TIMES (
	TIME_ID		VARCHAR2(10) NOT NULL,
	TIME_TYPE	VARCHAR2(10) NOT NULL, -- crash, holiday, weekend, improve, daily
	START_DATE	VARCHAR2(8),
	START_TIME	VARCHAR2(6) NOT NULL,
	END_DATE	VARCHAR2(8),
	END_TIME		VARCHAR2(6) NOT NULL,
	DESCRIPTION	VARCHAR2(100),
	CONSTRAINT PK_RESTRICTED_TIMES PRIMARY KEY(TIME_ID)
);

CREATE TABLE RESTRICTED_TIMES_RESOURCES (
	TIME_ID VARCHAR2(10) NOT NULL,
	RESOURCE_ID VARCHAR2(10) NOT NULL,
	CONSTRAINT PK_RESTRICTED_TIMES_RESOURCES  PRIMARY KEY(TIME_ID, RESOURCE_ID),
	CONSTRAINT FK_TIMES_RESOURCES_TIME_ID FOREIGN KEY (TIME_ID) REFERENCES RESTRICTED_TIMES(TIME_ID),
	CONSTRAINT FK_TIMES_RESOURCES_RESOURCE_ID FOREIGN KEY(RESOURCE_ID) REFERENCES SECURED_RESOURCES(RESOURCE_ID)
);

CREATE TABLE TIMES_RESOURCES_EXCLUSION (
	TIME_ID VARCHAR2(10) NOT NULL,
	RESOURCE_ID VARCHAR2(10) NOT NULL,
	ROLE_ID	VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_EXCLUSION  PRIMARY KEY(TIME_ID, RESOURCE_ID, ROLE_ID),
	CONSTRAINT FK_EXCLUSION_TIME_ID FOREIGN KEY (TIME_ID) REFERENCES RESTRICTED_TIMES(TIME_ID),
	CONSTRAINT FK_EXCLUSION_RESOURCE_ID FOREIGN KEY(RESOURCE_ID) REFERENCES SECURED_RESOURCES(RESOURCE_ID),
	CONSTRAINT FK_EXCLUSION_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID)
);


CREATE TABLE RESTRICTED_TIMES_ROLES (
	TIME_ID VARCHAR2(10) NOT NULL,
	ROLE_ID VARCHAR2(50) NOT NULL,
	CONSTRAINT PK_RESTRICTED_TIMES_ROLES  PRIMARY KEY(TIME_ID, ROLE_ID),
	CONSTRAINT FK_TIMES_ROLES_TIME_ID FOREIGN KEY (TIME_ID) REFERENCES RESTRICTED_TIMES(TIME_ID),
	CONSTRAINT FK_TIMES_ROLES_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

CREATE TABLE VIEW_RESOURCES  (
	VIEW_RESOURCE_ID 	VARCHAR2(50) NOT NULL,	-- ex.) LOGI_001
	CATEGORY	VARCHAR2(255),		-- ex.) 물류 > 입고관리
	VIEW_NAME	VARCHAR2(50) NOT NULL,	-- ex.) 미입고현황
	DESCRIPTION	VARCHAR2(255) NOT NULL,	-- ex.) 입고되지 않은 주문 리스트
	VIEW_INFO	VARCHAR2(255),		-- ex.) 화면에 대한 추가 정보
	VIEW_TYPE	VARCHAR2(10) NOT NULL,
	VISIBLE		VARCHAR2(1) NOT NULL,
	CONSTRAINT PK_VIEW_RESOURCES  PRIMARY KEY(VIEW_RESOURCE_ID)
);

CREATE TABLE VIEW_RESOURCES_MAPPING  (
	VIEW_RESOURCE_ID VARCHAR2(50) NOT NULL,
	REF_ID VARCHAR2(50) NOT NULL,		-- ex.) ROLE_ID or USER_ID
	MASK INTEGER NOT NULL,			-- ex.) 1(R), 2(W), 4(C), 8(D), 16(A)
	PERMISSIONS VARCHAR2(255) NOT NULL,	-- ex.) READ, WRITE, CREATE, DELETE, ADMINISTRATION
	REF_TYPE VARCHAR2(10) NOT NULL,		-- ex.) ROLE or USER [todo:// or GROUP]
	CONSTRAINT PK_VIEW_RESOURCES_MAPPING  PRIMARY KEY(VIEW_RESOURCE_ID, REF_ID),
	CONSTRAINT FK_MAPPING_VIEW_RESOURCE_ID  FOREIGN KEY (VIEW_RESOURCE_ID) REFERENCES VIEW_RESOURCES (VIEW_RESOURCE_ID)
);

CREATE TABLE VIEW_HIERARCHY	(
	PARENT_VIEW	VARCHAR2(50) NOT NULL,
	CHILD_VIEW	VARCHAR2(50) NOT NULL,
	CREATE_DATE VARCHAR2(8),
	MODIFY_DATE VARCHAR2(8),
	CONSTRAINT PK_VIEW_HIERARCHY PRIMARY KEY(PARENT_VIEW, CHILD_VIEW),
	CONSTRAINT FK_VIEW1 FOREIGN KEY (PARENT_VIEW) REFERENCES VIEW_RESOURCES (VIEW_RESOURCE_ID), 
	CONSTRAINT FK_VIEW2 FOREIGN KEY (CHILD_VIEW) REFERENCES VIEW_RESOURCES (VIEW_RESOURCE_ID)
);

CREATE TABLE IDS ( 
  TABLE_NAME  VARCHAR2 (16)  NOT NULL, 
  NEXT_ID     NUMBER (30)   NOT NULL, 
  PRIMARY KEY ( TABLE_NAME ) ) ;
  
CREATE TABLE CANDIDATE_SECURED_RESOURCES (
	CANDIDATE_RESOURCE_ID	NUMBER(10)		NOT NULL,
	BEANID					VARCHAR2(128),
	PACKAGES				VARCHAR2(128)	NOT NULL,
	CLASSES					VARCHAR2(128),
	METHOD					VARCHAR2(128),
	PARAMETER				VARCHAR2(128),
	REQUESTMAPPING			VARCHAR2(128),
	POINTCUT				VARCHAR2(128),
	CANDIDATE_RESOURCE_TYPE	VARCHAR2(10)	NOT NULL,
	CONSTRAINT	CANDIDATE_SECURED_RESOURCES_PK	PRIMARY KEY(CANDIDATE_RESOURCE_ID)
);

CREATE TABLE CATEGORY (
	CATEGORY_NO				VARCHAR(16)		NOT NULL,
	CATEGORY_NAME			VARCHAR(50)		NOT NULL,
	CATEGORY_DESC			VARCHAR(100),
	USE_YN					CHAR(1),
	REG_ID					VARCHAR(20),
	REG_DATE				DATE,
	MODIFY_ID				VARCHAR(20),
	MODIFY_DATE				DATE,
	CONSTRAINT PK_CATEGORY PRIMARY KEY(CATEGORY_NO)
);

CREATE TABLE PRODUCT (
	PROD_NO					VARCHAR(16)		NOT NULL,
	PROD_NAME				VARCHAR(100)	NOT NULL,
	SELLER_ID				VARCHAR(20),
	CATEGORY_NO				VARCHAR(16),
	PROD_DETAIL				VARCHAR(200),
	MANUFACTURE_DAY			VARCHAR(8),
	AS_YN					CHAR(1),
	SELL_QUANTITY			NUMERIC(5),
	SELL_AMOUNT				NUMERIC(10),
	IMAGE_FILE				VARCHAR(100),
	REG_DATE				DATE,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(PROD_NO),
	CONSTRAINT FK_PRODUCT FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);
